base_url = "https://elyhaka.github.io"
compile_sass = true
highlight_code = true
highlight_theme = "gruvbox-dark"
build_search_index = true
generate_feed = true

[extra]
# Put all your custom variables here
